### ISSUE TITLE
Millora

### ISSUE THREAD

**Issue by joanpardogine** [xcalle/Calle-Rubio-A06U#1]
Hola @Rubiioo i @xcalle 

En el repositori demanava:

> Cal que al **```README.md```** del vostre repositori, com a mínim aparegui el següent:
> 
> * Taula amb els membres del grup
> 
> |Nom alumne|Nom de github|
> |---|---|
> |Iván Nieto||
> |Vladi Bellavista||
> |Rubén Martinez||
> 
> * Diagrama MER de la vostra proposta de la base de dades
> 
> * Comanda sql per crear la base de dades
> 
> * Comanda sql per crear la primera de les taules de la base de dades
> 
> * Comanda sql per afegir registres a la primera de les taules de la base de dades

- [ ] taula membres.
- [x] Diagrama **MER**
- [ ] Comanda sql per crear la base de dades
- [x] Comanda sql per crear la primera de les taules de la base de dades
- [x] Comanda sql per afegir registres a la primera de les taules de la base de dades 

Tan bon punt estigui fet el que us falta, si us plau afegiu un comentari en aquest **```issue```**, anomenant-me, i indicant-me que ja puc acabar la correcció.

Moltes gràcies
Joan

**Comment by joanpardogine** [comment]
Hola @Rubiioo i @xcalle 

Ja fa tres dies del **`issue`** (**[joanpardogine](https://github.com/joanpardogine) commented [3 days ago](https://github.com/xcalle/Calle-Rubio-A06U/issues/1#issue-2036143083)**) i encara no m'heu dit res?!?!

Espero que em digueu alguna cosa al més aviat possible.

Moltes gràcies
Joan

**Comment by Rubiioo** [comment]
Hola Joan,

Si, ya em corregit el que estaba malament.

Gracies.

Eric Rubio

Missatge de joanpardogine ***@***.***> del dia dl., 8 de gen.
2024 a les 17:53:

**Comment by joanpardogine** [comment]
Hola @Rubiioo i @xcalle,

Tot i que no està **TOT** fet, procedeixo a tancar l'**`issue`**. 

Moltes gràcies
Joan
